### ISSUE TITLE
Support binary for Mac M1 (ARM)

### ISSUE THREAD

**Issue by tunguyen9889** [controlplaneio/kubectl-kubesec#73]
Can I request for support on Mac M1 (ARM)? I'm facing this issue when install the plugin via `krew`:

```
➜  ~ kubectl krew install kubesec-scan
Updated the local copy of plugin index.
Installing plugin: kubesec-scan
W1002 10:37:42.241667   52901 install.go:164] failed to install plugin "kubesec-scan": plugin "kubesec-scan" does not offer installation for this platform
F1002 10:37:42.241724   52901 root.go:79] failed to install some plugins: [kubesec-scan]: plugin "kubesec-scan" does not offer installation for this platform
➜  ~ uname -a
Darwin Jamess-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

Thanks!

**Comment by nicolas-g** [comment]
+1

**Comment by spiarh** [comment]
We have released a new version with support for M1 here: https://github.com/controlplaneio/kubectl-kubesec/releases/tag/v1.1.0

**Comment by tunguyen9889** [comment]
Hi @spiarh, thanks for working on it! Could you please update the version in krew as well? I still see `v1.0.2`:

```
$ kubectl krew update
Updated the local copy of plugin index.

$ kubectl krew info kubesec-scan
NAME: kubesec-scan
INDEX: default
VERSION: v1.0.2
HOMEPAGE: https://github.com/controlplaneio/kubectl-kubesec
DESCRIPTION:
This plugin uploads the specified Kubernetes resource’s API representation
to https://kubesec.io/ for security best practices scanning.
```

**Comment by spiarh** [comment]
@tunguyen9889 I've created a PR to update it (just waiting on the CLA on our side):  https://github.com/kubernetes-sigs/krew-index/pull/2915

**Comment by tunguyen9889** [comment]
awesome, thank you so much!

**Comment by tunguyen9889** [comment]
@spiarh I'm able to install kubesec-scan in my M1 Mac with `krew` now. Thank you!
